name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: 调试 - 列出文件结构
        run: |
          pwd
          ls -la
          find . -name "setupTests.ts" # 专门查找这个文件
          find . -name "jest.config.js" # 专门查找jest配置文件

      - name: 调试 - 查看 Jest 配置
        run: |
          npx jest --showConfig | grep -i "rootDir\|setupFilesAfterEnv" # 查看Jest最终使用的配置

      - name: Clear Jest cache
        run: npx jest --clearCache || true

      - name: Run tests
        run: npm run test

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
