name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clear Jest cache
        run: npx jest --clearCache || true

      - name: Run tests
        run: npm run test

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
